
[font]
size = 12

[font.bold]
family = "OverpassM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "OverpassM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "OverpassM Nerd Font"
style = "Italic"

[font.normal]
family = "OverpassM Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.96

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
